### ISSUE TITLE
Using this in other people's projects

### ISSUE THREAD

**Issue by MarkusSecundus** [lordconstant/SubclassPropertyDrawer#1]
Hi,
I'm asking because this repo isn't under any opensource or other license that would make that matter clear, and I can't find any better way to make contact - is it ok for me to use your work and modify it as part of my own project ([physics based swordfighting sim that I do for my bachelors and is under MIT license](https://github.com/MarkusSecundus/PhysicsSwordfight))? And if yes, are you OK with the way I'm giving you credits? (in main [README ](https://github.com/MarkusSecundus/PhysicsSwordfight/blob/master/README.md)+ doccomment on each one of your classes [like this](https://github.com/MarkusSecundus/PhysicsSwordfight/blob/master/Assets/ExternalAssets/SubclassPropertyDrawer/Editor/SubclassPropertyDrawer.cs) )

**Comment by lordconstant** [comment]
Sorry for slow response, no need to give credit use it however you want. I'll update it with an open license though thanks for the heads up :)
