### ISSUE TITLE
Doesnt work with [TextArea]

### ISSUE THREAD

**Issue by celojevic** [lordconstant/SubclassPropertyDrawer#2]
First of all, big fan of this package, honestly a mandatory thing to have and crazy how Unity doesnt have it built-in

There is an issue with the [TextArea]  attribute on a string within a derived class of the subclass. However, the odd thing is that nested classes with the same attribute work just fine. See my attached image
![image](https://github.com/lordconstant/SubclassPropertyDrawer/assets/61945370/bd9f1609-da42-4a95-aaf9-edff1ead1de5)

Below is how Im using the [Subclass] attribute and its contents:
`
// dialogue script
        [Subclass(IsList = true)]
        public List<DialogueOptionBase> Options = new List<DialogueOptionBase>();

...

// derived class
    [System.Serializable]
    public class TalkOption : DialogueOptionBase
    {

        [System.Serializable]
        public class TalkOptionChoice
        {
           // works with Subclass drawer
            [TextArea]
            public string Text;
            public int ToNodeId;

            public TalkOptionChoice(TalkOptionChoice copy)
            {
                this.Text = copy.Text;
                this.ToNodeId = copy.ToNodeId;
            }
        }

        // doesnt work with subclass drawer
        [TextArea]
        public string Text;
        public TalkOptionChoice[] Options;`

**Comment by lordconstant** [comment]
I think I fixed this on one of my projects, I'll have a search later today & get it updated

**Comment by lordconstant** [comment]
Should be fixed on latest!
I also added changes that allow the type list to include to base type of desired.

The exact change that fixed this was at line 99, just setting the height for the field area.

![image](https://github.com/lordconstant/SubclassPropertyDrawer/assets/5872279/d49c0a0f-1aa8-4df4-a8f1-8c0d038a97a1)
